# Generated by Django 3.1.5 on 2021-03-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iConso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fs_grouping_master',
            name='fs_show_status',
        ),
    ]
