# Generated by Django 3.1.5 on 2021-03-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iConso', '0002_remove_fs_grouping_master_fs_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coa_master',
            name='fs_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='COA_Master', to='iConso.fs_grouping_master'),
            preserve_default=False,
        ),
    ]
