# Generated by Django 3.1.5 on 2021-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iConso', '0004_auto_20210329_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_master',
            name='plan_code',
            field=models.CharField(max_length=100),
        ),
    ]
